### ISSUE TITLE
LGPL

### ISSUE THREAD

**Issue by DaveJarvis** [LoboEvolution/CobraEvolution#2]
Any chance of releasing this under LGPL, or any other non-strong-copyleft license? Apache 2, MIT, BSD, etc.?

**Comment by Thihup** [comment]
@oswetto Could you consider this?

**Comment by oswetto** [comment]
@DaveJarvis @Thihup Project moved user MIT license.

**Comment by DaveJarvis** [comment]
> Project moved user MIT license.

Do the source files need to change as well? I think many of them state GPL or LGPL?

**Comment by oswetto** [comment]
I have updated all files :-)
